[package]
name = "fiber-json-types"
version = "0.7.1"
edition = "2021"
description = "JSON-serializable types for the Fiber Network Node RPC API"

[dependencies]
fiber-types = { path = "../fiber-types" }
ckb-jsonrpc-types = "0.202.0"
ckb-types = "0.202.0"
hex = "0.4.3"
lightning-invoice = "0.33"
molecule = { version = "0.8.0", default-features = false }
secp256k1 = { version = "0.30.0", features = ["serde", "recovery"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_with = { version = "3.7.0", features = ["macros"] }
tentacle = { version = "0.7", default-features = false, features = ["tokio-runtime", "tokio-timer"] }

[lints.clippy]
expect-fun-call = "allow"
needless-return = "allow"
upper-case-acronyms = "allow"
